image: alpine/edge

secrets:
  - f9b0470f-3ea4-4b49-aeb9-99e9f48d75e5

tasks:
  - mirror-to-github: |
      ssh-keyscan github.com >> ~/.ssh/known_hosts
      cd start.m1n.land
      git remote add github git@github.com:M1n-74316D65/start.m1n.land.git || true
      git push --mirror github

